### PR TITLE
Fix typos and remove XDA Labs link since Labs has been discontinued

### PR DESCRIPTION
**Pull request by erayrafet**
* https://www.xda-developers.com/update-xda-labs/
* The Play Store now has a dark theme.

### CODE REVIEW

**Comment by znbaboy** [comment]
Also please add an auto update feature in the app since XDA labs is discontinued.

**Comment by erayrafet** [comment]
> Also please add an auto update feature in the app since XDA labs is discontinued. 

You can receive emails when future updates get uploaded to GitHub.
https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/about-notifications

**Comment by znbaboy** [comment]
> 
> 
> > Also please add an auto update feature in the app since XDA labs is discontinued.
> 
> You can receive emails when future updates get uploaded to GitHub.
> https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/about-notifications

I suppose. Not a very elegant solution though,

**Comment by erayrafet** [comment]
> > > Also please add an auto update feature in the app since XDA labs is discontinued.
> > 
> > 
> > You can receive emails when future updates get uploaded to GitHub.
> > https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/about-notifications
> 
> I suppose. Not a very elegant solution though,

Well, it is what it is.

**Comment by znbaboy** [comment]
> > > > Also please add an auto update feature in the app since XDA labs is discontinued.
> > > 
> > > 
> > > You can receive emails when future updates get uploaded to GitHub.
> > > https://docs.github.com/en/free-pro-team@latest/github/managing-subscriptions-and-notifications-on-github/about-notifications
> > 
> > 
> > I suppose. Not a very elegant solution though,
> 
> Well, it is what it is.

And thats why I'm here hoping for a better implementation xD

**Comment by KieronQuinn** [comment]
This is no longer required due to the rewrite, thanks for the PR though.

However, for future reference, "Licence" is valid British English, "License" is the US spelling. I'm British, so I tend to use that.

**Comment by erayrafet** [comment]
> This is no longer required due to the rewrite, thanks for the PR though.
> 
> However, for future reference, "Licence" is valid British English, "License" is the US spelling. I'm British, so I tend to use that. 

Okay, cool.

**Pull request closed without merging**
